### ISSUE TITLE
DAI Feedback (TODO: Close and reopen separate issues for the remaining work)

### ISSUE THREAD

**Issue by Ovich** [opendidac/opendidac#69]
Feedback from Ludovic Delafontaine

Priority
- [x] Student end session -> In order to allow the student to leave the session he must click on the button "End" preventing him to rejoin after hes leaves. 
- [x] List student in "in-progress" professor page that displays this status with the possibility to manage it. 
- [x] Groups cannot be renamed: Ludo went with a group name 2022-2023 and would like to make it more generic in order to reuse the question base year after year

Improvement
- [x] Take Exam : First page 0 with conditions
- [ ] Collections: Chose between deterministic ordering or shuffle. 
- [ ] Deterministic Ordering: As is -> change the order using drag and drop
- [ ] Shuffle: Each student different question ordering -> drag n drop disabled
- [ ] Code Question -> possibility to update the container entrypoint, withEntry point allows to write a custom entry point command, it enough to just add an optional field in Setup
- [x] Essay -> add expected answer -> right zone
- [x] Question Preview Panel in the list -> right zone, view button -> display student view 
- [ ] Question Variants -> When reusing the question next year, change a question a bit to be different than last year.

 Nice to Have
- [ ] CountDown active pull
- [ ] Grids: clickable row unclear -> add action button to open the row -> collections + jam sessions
- [ ] Jam Sessions -> Change the icons delete to archive
- [ ] JamSession Finalize in Draft missleading -> to remove
- [ ] JamSession New -> remove Student Registration
- [ ] Code Question -> Before All focus the end of input -> debounche related
- [ ] Java Code Question -> OpenJDK deprecated move to eclipse-temurin:latest (https://whichjdk.com/)
- [ ] Questions List -> remove content
- [ ] Add title on the content field in admin
- [ ] Add helper_texts all around

Issues
- [x] Code Question -> When removing "image" setup do not display
- [x] Question -> Add default pts in question, that would prefill the pts in collection when you add a question
- [x] ContentEditor -> markdown not correctly interpreting lists
- [ ] Code Files -> Possibility to have different type of files than TEXT -> Binary files. 
- [ ] Code File Manager -> unclear that pull from solution erase all the files
- [ ] Question MultiChoice -> add possibility to have 3 states : true, false and empty.  

First TE feedback
- [x] Schedule wont accept 0 minutes on the minutes field
Over all good, some suggestions by the students
- [x] The markdown not dispaying lists properly has caused issues during the markdown related question during exam
- [x] Essay Question and possibly Code -> When page overflow no scroll
- [x] Grading Essay -> see markdown code and interpretation
- [x] Code, database -> BottomPannel layout (CodeCheck) when open goes over the files and hides part of them, it was unclear for several students that they need to close the BottomPannel to see the code that is under.. Test with flexible layout.
- [x] Code Question -> When the question has no tests setup the codecheck always displays "all tests passed"
        - If 0 tests button should be "Run" and no tests related messaged displayed. 
        - remove the label from the field "beforeAll"

Student Feedback from TE1

- [ ] They would like a mechanism to mark a question in case they did not finish and would like to go back to it. 
- [x] Question Paging -> add tooltip with type, title and points
- [ ] OR Add SidePanel with index that display the type, title, points and submission status -> maybe get rid of current paging (similar to wikipedia)

Grading

- [x] Comment should persist in database on change -> now if you dont sign and change the student you lose your comment
- [x] Remove Filters
- [ ] MultiChoice -> when the student does not check the option that is correct it should display in red.
                 - Split screen where the solution is on the rist and student options on the left
                 - When an option does not match it should be red and otherwise green (no gray)
                 - Add summary that display correctness of the student answer -> 
 - [x] Success Rate - Add tooltip for formula

Analytics
- [ ] Issue with question having 0 pts. 
- [ ] When in-progress add link to analytics
- [ ] Add list of students in in-progress with submission status

**Comment by Ovich** [comment]
We have splited what remains relevant in this issue into separate issues:

#400 #403 #402 #401 

thus closing this issue
